# Generated by Django 5.2.8 on 2025-12-03 16:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("car_showroom", "0002_initial"),
        ("dealers", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="provider",
            name="user",
            field=models.OneToOneField(
                limit_choices_to={"user_type": "provider"},
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="providercars",
            name="car",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="dealers.car"
            ),
        ),
        migrations.AddField(
            model_name="providercars",
            name="provider",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="dealers.provider"
            ),
        ),
        migrations.AddField(
            model_name="provider",
            name="cars",
            field=models.ManyToManyField(
                through="dealers.ProviderCars", to="dealers.car"
            ),
        ),
        migrations.AddField(
            model_name="providerdiscount",
            name="provider",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="dealers.provider"
            ),
        ),
        migrations.AddField(
            model_name="providercars",
            name="discount",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="dealers.providerdiscount",
            ),
        ),
        migrations.AddField(
            model_name="providersaleshistory",
            name="car",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="dealers.car"
            ),
        ),
        migrations.AddField(
            model_name="providersaleshistory",
            name="provider",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="dealers.provider"
            ),
        ),
        migrations.AddField(
            model_name="providersaleshistory",
            name="showroom",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="car_showroom.carshowroom",
            ),
        ),
    ]
