# Generated by Django 5.2.8 on 2026-01-06 12:52

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import models, migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dealers", "0004_alter_providerorder_order_status_max_length"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name="providerorder",
            old_name="order_status",
            new_name="status",
        ),
        migrations.AlterField(
            model_name="car",
            name="year",
            field=models.PositiveIntegerField(
                validators=[
                    django.core.validators.MinValueValidator(1900),
                    django.core.validators.MaxValueValidator(2026),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="provider",
            name="owner_user",
            field=models.OneToOneField(
                limit_choices_to={"type": "provider"},
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="provider",
            name="year_founded",
            field=models.PositiveIntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1800),
                    django.core.validators.MaxValueValidator(2026),
                ],
            ),
        ),
    ]
