# Generated by Django 5.2.8 on 2026-02-18 20:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dealers", "0005_rename_order_status_providerorder_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="providerorder",
            name="car",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="dealers.providercar"
            ),
        ),
    ]
