# Generated by Django 5.2.8 on 2026-02-27 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dealers", "0006_alter_providerorder_car"),
    ]

    operations = [
        migrations.AlterField(
            model_name="providercar",
            name="car_quantity",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
