# Generated by Django 5.2.8 on 2025-12-08 15:36

import django.core.validators
from django.db import models, migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="balance_currency",
        ),
        migrations.AlterField(
            model_name="user",
            name="balance",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=12,
                validators=[django.core.validators.MinValueValidator(0.0)],
            ),
        ),
    ]
