# Generated by Django 5.2.8 on 2026-01-06 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_remove_user_balance_currency_alter_user_balance"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="user_type",
            new_name="type",
        ),
    ]
