# Generated by Django 5.2.8 on 2025-12-03 16:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("car_showroom", "0001_initial"),
        ("customers", "0001_initial"),
        ("dealers", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="carshowroom",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="carshowroomdiscount",
            name="showroom",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="car_showroom.carshowroom",
            ),
        ),
        migrations.AddField(
            model_name="carshowroomsaleshistory",
            name="car",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="dealers.car"
            ),
        ),
        migrations.AddField(
            model_name="carshowroomsaleshistory",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="customers.customer"
            ),
        ),
        migrations.AddField(
            model_name="carshowroomsaleshistory",
            name="showroom",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="car_showroom.carshowroom",
            ),
        ),
        migrations.AddField(
            model_name="showroomcars",
            name="car",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="dealers.car"
            ),
        ),
        migrations.AddField(
            model_name="showroomcars",
            name="discount",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="car_showroom.carshowroomdiscount",
            ),
        ),
        migrations.AddField(
            model_name="showroomcars",
            name="showroom",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="car_showroom.carshowroom",
            ),
        ),
        migrations.AddField(
            model_name="carshowroom",
            name="cars",
            field=models.ManyToManyField(
                through="car_showroom.ShowroomCars", to="dealers.car"
            ),
        ),
    ]
