# Generated by Django 5.2.8 on 2025-12-07 08:59

import django.db.models.deletion
from django.conf import settings
from django.db import models, migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("car_showrooms", "0001_initial"),
        ("dealers", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="carshowroom",
            name="owner_user",
            field=models.OneToOneField(
                limit_choices_to={"user_type": "showroom"},
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="carshowroomorder",
            name="car",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="dealers.car"
            ),
        ),
        migrations.AddField(
            model_name="carshowroomorder",
            name="car_buyer",
            field=models.ForeignKey(
                limit_choices_to={"user_type": "showroom"},
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="carshowroomorder",
            name="showroom",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="car_showrooms.carshowroom",
            ),
        ),
        migrations.AddField(
            model_name="showroomcar",
            name="car",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="dealers.car"
            ),
        ),
        migrations.AddField(
            model_name="showroomcar",
            name="discount",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="car_showrooms.discount",
            ),
        ),
        migrations.AddField(
            model_name="showroomcar",
            name="showroom",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="car_showrooms.carshowroom",
            ),
        ),
        migrations.AddField(
            model_name="carshowroom",
            name="cars",
            field=models.ManyToManyField(
                through="car_showrooms.ShowroomCar", to="dealers.car"
            ),
        ),
    ]
