# Generated by Django 5.2.8 on 2025-12-08 15:56

import django.core.validators
from django.db import models, migrations


class Migration(migrations.Migration):

    dependencies = [
        ("car_showrooms", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="carshowroomorder",
            name="price_currency",
        ),
        migrations.RemoveField(
            model_name="showroomcar",
            name="price_currency",
        ),
        migrations.AlterField(
            model_name="carshowroomorder",
            name="price",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=12,
                validators=[django.core.validators.MinValueValidator(0.0)],
            ),
        ),
        migrations.AlterField(
            model_name="showroomcar",
            name="price",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=12,
                validators=[django.core.validators.MinValueValidator(0.0)],
            ),
        ),
    ]
