# Generated by Django 5.2.8 on 2026-01-06 12:52

import django.db.models.deletion
from django.conf import settings
from django.db import models, migrations


class Migration(migrations.Migration):

    dependencies = [
        ("car_showrooms", "0004_alter_carshowroomorder_order_status_max_length"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name="carshowroomorder",
            old_name="order_status",
            new_name="status",
        ),
        migrations.AlterField(
            model_name="carshowroom",
            name="owner_user",
            field=models.OneToOneField(
                limit_choices_to={"type": "showroom"},
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="carshowroomorder",
            name="car_buyer",
            field=models.ForeignKey(
                limit_choices_to={"type": "showroom"},
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
