# Generated by Django 5.2.8 on 2026-02-02 16:25

import django.db.models.deletion
from django.conf import settings
from django.db import models, migrations


class Migration(migrations.Migration):

    dependencies = [
        ("car_showrooms", "0006_discount_creator_showroomcar_is_published"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="discount",
            name="creator",
            field=models.ForeignKey(
                limit_choices_to={"type": ("showroom", "provider")},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="discounts",
                related_query_name="discount",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
