# Generated by Django 5.2.8 on 2026-02-02 21:14

import django.core.validators
import django.db.models.deletion
from django.db import models, migrations


class Migration(migrations.Migration):

    dependencies = [
        ("car_showrooms", "0007_alter_discount_creator"),
    ]

    operations = [
        migrations.AlterField(
            model_name="discount",
            name="creator",
            field=models.ForeignKey(
                limit_choices_to={"type": ("showroom", "provider")},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="discounts",
                related_query_name="discount",
                to="car_showrooms.carshowroom",
            ),
        ),
        migrations.AlterField(
            model_name="discount",
            name="percent",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=4,
                validators=[
                    django.core.validators.MinValueValidator(0.0),
                    django.core.validators.MaxValueValidator(100.0),
                ],
            ),
        ),
    ]
