# Generated by Django 5.2.8 on 2026-02-02 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("car_showrooms", "0008_alter_discount_creator_alter_discount_percent"),
    ]

    operations = [
        migrations.RenameField(
            model_name="discount",
            old_name="creator",
            new_name="showroom",
        ),
    ]
