# Generated by Django 5.2.8 on 2026-02-03 21:50

import django.db.models.deletion
from django.conf import settings
from django.db import models, migrations


class Migration(migrations.Migration):

    dependencies = [
        ("car_showrooms", "0009_rename_creator_discount_showroom"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="carshowroomorder",
            name="car_buyer",
            field=models.ForeignKey(
                limit_choices_to={"type": "customer"},
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
