# Generated by Django 5.2.8 on 2026-02-03 22:11

import django.db.models.deletion
from django.db import models, migrations


class Migration(migrations.Migration):

    dependencies = [
        ("car_showrooms", "0010_alter_carshowroomorder_car_buyer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="carshowroomorder",
            name="car",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="car_showrooms.showroomcar",
            ),
        ),
    ]
