# Generated by Django 5.2.8 on 2026-02-05 21:32

import django.db.models.deletion
from django.conf import settings
from django.db import models, migrations


class Migration(migrations.Migration):

    dependencies = [
        ("car_showrooms", "0011_alter_carshowroomorder_car"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="discount",
            name="showroom",
            field=models.ForeignKey(
                limit_choices_to={"type": ("showroom", "provider")},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="discounts",
                related_query_name="discount",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
