# Generated by Django 5.2.8 on 2026-02-05 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("car_showrooms", "0012_alter_discount_showroom"),
    ]

    operations = [
        migrations.RenameField(
            model_name="discount",
            old_name="showroom",
            new_name="owner_user",
        ),
    ]
