# Generated by Django 5.2.8 on 2026-02-27 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("car_showrooms", "0013_rename_showroom_discount_owner_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="showroomcar",
            name="car_quantity",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
